# Generated by Django 5.1.1 on 2024-10-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="conversation_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
